server:
  port: 7002  #该 Module 的端口号

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称，
  server:
    enable-self-preservation: true # false 关闭 Eureka 的自我保护机制，默认是开启,一般不建议大家修改

  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版服务注册中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/ #将这个 Eureka Server 注册到 7001 和 7003 上
